name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
        
    - name: Install Node
    - uses: actions/sertup-node@v2-beta
      with:
        version: 12 
        
    - name: Installing Surge
      uses: npm install -g surge
  
    - name: deploying using surge
      uses: surge ./ bootcamp-class1-007.surge.sh --token $ {{ secrets.SURGE_TOKEN }}
